apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-prefect
spec:
  ingressClassName: traefik
  rules:
  - host: prefect.axiusvm.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prefect-server
            port:
              number: 4200
