apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-openobs
spec:
  ingressClassName: traefik
  rules:
  - host: obs.axiusvm.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openobserve
            port:
              number: 5080
