apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-test-deployment
  labels:
    app: go-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-test
  template:
    metadata:
      labels:
        app: go-test
    spec:
      containers:
      - name: go-test
        image: localhost/go-test:latest
        imagePullPolicy: IfNotPresent
