apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: whoami
 namespace: whoami
spec:
 tls:
   - hosts:
       - myapp.domain.com      #Specify cert for host
     secretName: my-app-cert-secret # The secret set in the kubectl -n kube-system create secret tls default-ingress-cert... command
 rules:
   - host: myapp.domain.com 
     http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: svc-coffee
               port:
                 number: 80