apiVersion: traefik.containo.us/v1alpha1 #sets the DEFAULT trafic cert. Can be a wildcard cert.
kind: TLSStore
metadata:
  name: default
  namespace: kube-system

spec:
  defaultCertificate:
    secretName: default-ingress-cert