apiVersion: v1
kind: Service
metadata:
  name: pgdb
spec:
  clusterIP: None
  selector:
    app: pgdb
  ports:
  - name: http
    port: 5432
    targetPort: 5432

---

# create statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgdb
  labels:
    name: pgdb
spec:
  serviceName: pgdb
  replicas: 1
  selector:
    matchLabels:
      name: pgdb
      app: pgdb
  template:
    metadata:
      labels:
        name: pgdb
        app: pgdb
    spec:
      containers:
        - name: pgdb
          image: postgres:17.0-alpine
          env:
            - name: POSTGRES_DB
              value: srf_stag
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef: # get env from secret
                  name: pgdb-secrets # secret name
                  key: pgdb_user # secret key
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef: # get env from secret
                  name: pgdb-secrets # secret name
                  key: pgdb_password # secret key
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
              name: http
          volumeMounts:
          - name: dbdata
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: dbdata
          hostPath:
            # Ensure the file directory is created.
            path: /opt/dbdata
            type: DirectoryOrCreate